### ISSUE TITLE
Plot ROC curves for train/test/valid score

### ISSUE THREAD

**Issue by Sum02dean** [Sum02dean/STRINGSCORE#5]
Expect to see increasing off-diagonal profile for the score correctness (benchmark plot).

**Comment by Sum02dean** [comment]
Will need to get the intersection between the benchmark data and the train, and the test data to plot the benchmark statistics. 

```
https://github.com/Sum02dean/STRINGSCORE/blob/d7d6794f4002716e0747f504113648c07590e076/src/xgboost_model.py#L285-L287
```

**Comment by Sum02dean** [comment]
Plotting for human (train/test/valid) using balanced data:

![image](https://user-images.githubusercontent.com/36505689/148060645-3ef2ad0b-166f-4b02-b466-4df5c15e3ec6.png)

**Comment by Sum02dean** [comment]
Plotting on ecoli:

![image](https://user-images.githubusercontent.com/36505689/148062047-e4bb125e-98ac-422c-afef-5c73d0067bbd.png)

**Comment by Sum02dean** [comment]
Plotting on yeast - balanced, no noise, no COG split:

![image](https://user-images.githubusercontent.com/36505689/148065159-70e6ef21-708b-46bf-86b1-a79831e20031.png)

**Comment by damianszk** [comment]
Why we are looking at the balanced, no noise, no COG split?
It's the least interesting, as we know we have issues there. Unbalanced, noise, COG split is the cleanest one to see the performance.

But anyway... the question here is why these curves are so different. So we have training (logistic?), testing (diagonal), and validation (totally off). What's wrong with the validation...

**Comment by Sum02dean** [comment]
In order to identify issues in a systematic manner. I am performing the same analysis with:

* balanced, no noise, no cog 
* unbalanced, no noise, no cog
* unbalanced, noise, no cog
* unbalanced, noise, cog
